---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.27.1
    env:
      TZ: "${TIMEZONE}"
      DATABASE_HOST: '{{ include "common.names.fullname" .}}-postgresql'
      # DATABASE_USER: "{{ .Values.postgresql.postgresUsername }}"
      DATABASE_PASS: "{{ .Values.postgresql.auth.postgresPassword }}"
      DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
      MQTT_HOST: "mosquitto.home"
      MQTT_USERNAME: "${SECRET_TESLAMATE_MQTT_USERNAME}"
      MQTT_PASSWORD: "${SECRET_TESLAMATE_MQTT_PASSWORD}"
    podAnnotations:
      secret.reloader.stakater.com/reload: teslamate
    service:
      main:
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "teslamate.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: teslamate-config-v1
        mountPath: /opt/app/import
    postgresql:
      enabled: true
      postgresqlUsername: "${SECRET_TESLAMATE_DB_USER}"
      postgresqlPassword: "${SECRET_TESLAMATE_DB_PASS}"
      postgresqlDatabase: "${SECRET_TESLAMATE_DB}"
      persistence:
        enabled: true
        existingClaim: teslamate-db-v1
