---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: syncthing
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.21.0
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "syncthing.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: syncthing-config-v1
        mountPath: /var/syncthing
      sync:
        enabled: true
        type: hostPath
        hostPath: /mnt/home/syncthing/sync
        mountPath: /sync
